services:
  - type: web
    name: java-concepts-doc
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: NEON_URL
        sync: false
      - key: NEON_USER
        sync: false
      - key: NEON_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: neon
